- name: Container
  hosts: docker_host
  tasks:
    - name: Create container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image }}:{{ tag }}"
        cpus: 1
        memory: 512M
        hostname: "ubuntu"
        # To use storage limit the docker need storage setup with xfs and pquota
        # storage_opts:
        #   size: 10G
        networks:
          - name: "{{ network }}"
        state: started
        volumes:
          - "/caas/ssh_keys/{{ user_id }}/{{ container_name }}/authorized_keys:/root/.ssh/authorized_keys"
