- name: Container
  hosts: docker_host
  tasks:
    - name: Get container detail
      community.docker.docker_container_info:
        name: "{{ container_name }}"
      register: result
    - name: Delete container
      failed_when: result.exists == false
      community.docker.docker_container:
        name: "{{ container_name }}"
        keep_volumes: false
        state: absent
