- name: Nginx configuration
  hosts: vm
  tasks:
    - name: Create nginx configuration file
      ansible.builtin.template:
        src: templates/nginx_conf.j2
        dest: /etc/nginx/conf.d/{{ config_name }}.conf
        mode: "0644"
    # - name: Restart nginx
    #   ansible.builtin.service:
    #     name: nginx
    #     state: restarted
