- name: Nginx configuration
  hosts: vm
  tasks:
    - name: Delete nginx config
      ansible.builtin.file:
        path: /etc/nginx/conf.d/{{ config_name }}.conf
        state: absent
    - name: Delete nginx log
      ansible.builtin.file:
        path: /var/log/nginx/{{ container_name }}_{{ config_name }}.access.log
        state: absent
