- name: Nginx configuration
  hosts: docker_host
  gather_facts: false
  tasks:
    - name: Delete nginx config
      ansible.builtin.file:
        path: /etc/nginx/conf.d/{{ container_name }}_{{ config_id }}.conf
        state: absent
    - name: Delete nginx log
      ansible.builtin.file:
        path: /var/log/nginx/{{ container_name }}_{{ config_id }}.access.log
        state: absent
