- name: Edit Nginx configuration
  hosts: docker_host
  tasks:
    - name: Delete existing nginx config
      ansible.builtin.file:
        path: /etc/nginx/conf.d/{{ container_name }}_{{ config_id }}.conf
        state: absent
    - name: Create new nginx configuration file
      ansible.builtin.template:
        src: templates/nginx_conf.j2
        dest: /etc/nginx/conf.d/{{ container_name }}_{{ config_id }}.conf
        mode: "0644"
    # - name: Restart nginx
    #   ansible.builtin.service:
    #     name: nginx
    #     state: restarted
