import type { Metadata } from "next"
import { auth } from "@/lib/auth"
import { headers } from "next/headers"
import { permanentRedirect } from "next/navigation"

export const metadata: Metadata = {
  title: "CaaS",
  description: "Generated by create next app"
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth.api.getSession({
    headers: await headers()
  })

  if (session) {
    permanentRedirect("/console")
  }
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  )
}
