- name: DDocker Network
  hosts: docker_host
  tasks:
    - name: Create docker network
      community.docker.docker_network:
        name: "{{ network_name }}"
        ipam_config:
          - subnet: "{{ network_subnet }}"
            gateway: "{{ network_gateway }}"
        state: present
