- name: Ssh authorized_keys
  hosts: docker_host
  tasks:
    - name: Create directory for ssh keys
      ansible.builtin.file:
        path: /home/anish/caas/ssh_keys/{{ user_id }}/{{ ssh_key_name }}
        state: directory
        mode: "0755"
        owner: root
    - name: Create ssh authorized_keys file
      ansible.builtin.template:
        src: templates/authorized_keys.j2
        dest: /home/anish/caas/ssh_keys/{{ user_id }}/{{ ssh_key_name }}/authorized_keys
        mode: "0644"
        owner: root
