- name: Delete SSH authorized key file
  hosts: docker_host
  gather_facts: false
  tasks:
    - name: Delete SSH authorized key file
      ansible.builtin.shell: >
        rm -rf /caas/ssh_keys/{{ user_id }}/{{ container_name }}
