name: ImageBuilder

on:
  workflow_dispatch:
    inputs:
      publish:
        description: "Choose which application to build"
        required: true
        type: choice
        options:
          - MainApp
          - InfraBe
          - WsBe
      image_tag:
        description: "Tag of the image"
        required: true
        type: string

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push MainApp
        if: inputs.publish == 'MainApp'
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: aaraz/caas:${{ inputs.image_tag }}
          platforms: linux/amd64,linux/arm64
      - name: Build and push InfraBe
        if: inputs.publish == 'InfraBe'
        uses: docker/build-push-action@v5
        with:
          context: ./infra_be
          push: true
          tags: aaraz/caas:${{ inputs.image_tag }}
          platforms: linux/amd64,linux/arm64
      - name: Build and push WsBe
        if: inputs.publish == 'WsBe'
        uses: docker/build-push-action@v5
        with:
          context: ./ws_be
          push: true
          tags: aaraz/caas:${{ inputs.image_tag }}
          platforms: linux/amd64,linux/arm64
